### ISSUE TITLE
Any available step-by-step tutorial for this implementation? 

### ISSUE THREAD

**Issue by HongminWu** [markolalovic/latent-learning-robot#1]
Would you kindly add any lacking scripts for a comprehensive tutorial of robot skill leaning in latent space?

**Comment by markolalovic** [comment]
The repository contains only the simple deep autoencoder network design that can be applied to any DMP weight vectors. The code for simulation and execution is not available in the repository and it was written only for this specific task and this specific robot and is therefore irrelevant in general.

See the more comprehensive example using a publicly available Python library with a more general implementation of DMPs in README: [https://github.com/markolalovic/latent-learning-robot](https://github.com/markolalovic/latent-learning-robot)

You can also read the accompanying tutorials for the library here: [https://studywolf.wordpress.com/category/robotics/dynamic-movement-primitive/
](https://studywolf.wordpress.com/category/robotics/dynamic-movement-primitive/
)

For explanation of PoWER RL algorithm you can see the paper: [https://papers.nips.cc/paper/2008/file/7647966b7343c29048673252e490f736-Paper.pdf](https://papers.nips.cc/paper/2008/file/7647966b7343c29048673252e490f736-Paper.pdf)

The implementation of the algorithm is trivial.
